languageCode = "en-us"
title = "Jim & Shannon Angel | 2017"
baseurl = "https://jimandshan.com/"
theme = "prologue"

[params]
  name = "Jim & Shannon"
  description = "11/25/17"
  copyright = "Jim & Shannon Angel."

# Portfolio column one

[[params.portfolio1]]
  title = "SHANNON OSIKA"
  alt = ""
  source = "img/pic02.jpg"
  url = "#"

[[params.portfolio1]]
  title = "Rhoncus Semper"
  alt = ""
  source = "img/pic03.jpg"
  url = "#"
