languageCode = "en-us"
title = "Jim and Shannon Angel | 2017"
baseurl = "https://jimandshan.com/"
theme = "prologue"
googleAnalytics = "UA-100200937-1"
enableRobotsTXT = true

[params]
  name = "Jim and Shan"
  description = "11/25/17"
  copyright = "Jim and Shan"

# Portfolio column one

[[params.portfolio1]]
  title = "Bookings (All Resorts)"
  alt = ""
  source = "img/pic02.jpg"
  url = "http://www.bahia-principe.com/en/resorts-in-riviera-maya/"

# Portfolio column two

[[params.portfolio2]]
  title = "Hope to see you there!"
  alt = ""
  source = "img/pic04.jpg"
  url = "#"

# Portfolio column 3

[[params.portfolio3]]
  title = "Flights (Southwest)"
  alt = ""
  source = "img/pic06.jpg"
  url = "https://www.southwest.com/flight/shortcut/low-fare-search.html"
