languageCode = "en-us"
title = "Jim & Shannon Angel | 2017"
baseurl = "https://jimandshan.com/"
theme = "prologue"

[params]
  name = "Jim & Shannon"
  description = "11/25/17"
  copyright = "Jim & Shannon Angel."

# Portfolio column one

[[params.portfolio1]]
  title = "SHANNON OSIKA"
  alt = ""
  source = "img/pic02.jpg"
  url = "#"

# Portfolio column two

[[params.portfolio2]]
  title = "Magna Nullam"
  alt = ""
  source = "img/pic04.jpg"
  url = "#"

# Portfolio column 3

[[params.portfolio3]]
  title = "Dolor Penatibus"
  alt = ""
  source = "img/pic06.jpg"
  url = "#"
