languageCode = "en-us"
title = "Jim & Shannon Angel | 2017"
baseurl = "https://jimandshan.com/"
theme = "prologue"

[params]
  name = "Jim & Shannon"
  description = "11/25/17"
  copyright = "Jim & Shannon Angel."

# Portfolio column one

[[params.portfolio1]]
  title = "All Resorts (Bookings)"
  alt = ""
  source = "img/pic02.jpg"
  url = "http://www.bahia-principe.com/en/resorts-in-riviera-maya/"

# Portfolio column two

[[params.portfolio2]]
  title = "Hope to see you there!"
  alt = ""
  source = "img/pic04.jpg"
  url = "#"

# Portfolio column 3

[[params.portfolio3]]
  title = "Google Flight Search"
  alt = ""
  source = "img/pic06.jpg"
  url = "https://www.google.com/flights/flights-to-cancun.html"
